# To use in local development:
# - Run `pip3 install pre-commit` (or `brew install pre-commit`)
# - In the project root directory (where this file resides) run: `pre-commit install`
# - Done! The below hooks should now automatically run before commit (where applicable).

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_tflint
  - id: terraform_docs
